package com.cursojbpmej.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosContacto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Dirección")
	private java.lang.String direccion;
	@org.kie.api.definition.type.Label(value = "Correo electrónico")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Número telefónico")
	private java.math.BigInteger telefono;

	public DatosContacto() {
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.math.BigInteger getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.math.BigInteger telefono) {
		this.telefono = telefono;
	}

	public DatosContacto(java.lang.String direccion, java.lang.String email,
			java.math.BigInteger telefono) {
		this.direccion = direccion;
		this.email = email;
		this.telefono = telefono;
	}

}