package com.cursojbpmej.model.bo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fecha de nacimiento")
	private java.util.Date fechaNacimiento;
	@org.kie.api.definition.type.Label("Primeros nombres")
	private java.lang.String nombres;
	@org.kie.api.definition.type.Label("Primer apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label("Segundo apellido")
	private java.lang.String segundoApellido;
	@org.kie.api.definition.type.Label("Tipo DNI")
	private java.lang.String tipoDocumento;
	@org.kie.api.definition.type.Label("Número DNI")
	private java.math.BigInteger numeroDocumento;

	@org.kie.api.definition.type.Label("Aprobación de crédito")
	private String aprobado;

	public Persona() {
	}

	public java.util.Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.util.Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public java.lang.String getNombres() {
		return this.nombres;
	}

	public void setNombres(java.lang.String nombres) {
		this.nombres = nombres;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(java.lang.String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public java.lang.String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(java.lang.String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public java.math.BigInteger getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.math.BigInteger numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.lang.String getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(java.lang.String aprobado) {
		this.aprobado = aprobado;
	}

	public Persona(java.util.Date fechaNacimiento, java.lang.String nombres,
			java.lang.String primerApellido, java.lang.String segundoApellido,
			java.lang.String tipoDocumento,
			java.math.BigInteger numeroDocumento, java.lang.String aprobado) {
		this.fechaNacimiento = fechaNacimiento;
		this.nombres = nombres;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.aprobado = aprobado;
	}

}